#!/usr/bin/env bash

# black=#1e222a
# green=#7eca9c
# white=#abb2bf
# grey=#282c34
# blue=#7aa2f7
# red=#d47d85
# darkblue=#668ee3

icon=""
dayofweek=`date +%A`
dayofmonth=`date +%e`
month=`date +%B`
year=`date +%Y`

case $dayofmonth in
    1 | 21 | 31)
        suffix="st"
        ;;
    2 | 22)
        suffix="nd"
        ;;
    3 | 23)
        suffix="rd"
        ;;
    *)
        suffix="th"
        ;;
esac

fulldate="$dayofweek $dayofmonth$suffix of $month $year"

case $BLOCK_BUTTON in
    1) notify-send "$fulldate" ;;
    3) setsid --fork alacritty --class "calcurse,calcurse" -e calcurse ;;
esac

. /usr/local/bin/statusbar/colors

printf "^c$green^$icon$(date '+%l:%M%P')  "
